# Basic VINDRIKTNING pm25
substitutions:
  device_name: "vindriktning-pm1006"
  sensor_name: "Vindriktning PM1006"
  device_description: "IKEA VINDRIKTNING Particulate Matter Sensor with PM1006"
packages:
  device_base: !include common/device_base.yaml
esphome:
  name: ${device_name}
  comment: ${device_description}
esp8266:
  board: d1_mini
wifi:
  manual_ip:
    static_ip: 192.168.1.59
    gateway: 192.168.1.1
    subnet: 255.255.255.0
#SERIAL
uart:
- id: uart_a
  rx_pin: D4
  baud_rate: 9600
#
sensor:
  # PM1006
  - platform: pm1006
    uart_id: uart_a
    pm_2_5:
      name: ${sensor_name} PM25
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 50
            send_every: 15 
            send_first_at: 10
